### ISSUE TITLE
integrate clearml to track experiments 

### ISSUE THREAD

**Issue by mosheraboh** [BiomedSciAI/fuse-med-ml#188]

**Comment by SagiPolaczek** [comment]
Can we close it? 
@smartdanny added `def start_clearml_logger()` at `fuse.dl.lightning.pl_funcs.py` in #221

**Comment by SagiPolaczek** [comment]
What do you guys say? should we close it? @mosheraboh @smartdanny 

Another "issue" (not sure if that's the expected behavior) that I encountered with ClearML:
When we resume from checkpoint we plot only part of the graph (which makes it difficult to grasp the full picture).

For example:
![image](https://user-images.githubusercontent.com/56922146/236663146-c623b3cb-b86e-4de9-ab37-955bf0ff2fc4.png)

**Comment by SagiPolaczek** [comment]
The last solved by using setting
```
  reuse_last_task_id: False
  continue_last_task: True  
```
